name: Build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Why are we doing this?
      #
      # The hosted GitHub runners have free disk space split
      # between the root partition and a temporary partition,
      # leaving limited space for builds. We work around this
      # with easimon/maximize-build-space which creates a LVM
      # volume to combine the free space in both.
      #
      # We mount this new volume at /nix, and set TMPDIR so
      # all builds happen inside the volume.
      - name: Create mount point for Nix store
        run: |
          sudo mkdir /nix

      - name: Maximize disk space for builds
        uses: easimon/maximize-build-space@v7
        with:
          build-mount-path: /nix

      - name: Set Nix store ownership
        run: |
          sudo chown root:root /nix

      - uses: actions/checkout@v3.0.2

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Override nix-daemon build directory
        run: |
          sudo mkdir -p /nix/tmp
          sudo chmod ug=rwx,o=rwxt /nix/tmp

          sudo mkdir -p /etc/systemd/system/nix-daemon.service.d
          sudo tee /etc/systemd/system/nix-daemon.service.d/override.conf >/dev/null <<EOF
          [Service]
          Environment=TMPDIR=/nix/tmp
          EOF

          sudo systemctl daemon-reload
          sudo systemctl restart nix-daemon

      - name: Setup automatic caching
        uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install nix-build-uncached
        # Save evaluation time by pulling directly from cache.nixos.org
        # nixpkgs rev 104e8082de1b20f9d0e1f05b1028795ed0e0e4bc
        run: nix-env -i /nix/store/zl1krzl6rm321ss84riayyhyn0scr3xi-nix-build-uncached-1.1.1

      - name: Build overlay packages
        run: nix-build-uncached .ci/instantiate-overlay.nix
